name: Build LaTeX PDF (reserved)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    if: ${{ hashFiles('report/**/*.tex') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v3
        with:
          working_directory: report
          root_file: report.tex
          latexmk_use_lualatex: true
      - uses: actions/upload-artifact@v4
        with:
          name: built-report
          path: report/report.pdf
